name: ces_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get:
  get_storage:
  carousel_slider: ^4.2.1
  http:
  intl:
  flutter_form_builder:
  form_builder_validators:
  easy_stepper:

  cached_network_image:
  shimmer:
  # flutter_native_splash: ^2.3.1
  # flutter_svg:
  badges: ^3.1.1
  auto_size_text: ^3.0.0
  flutter_local_notifications:
  # firebase_auth:
  firebase_messaging: ^14.6.5
  firebase_core:
  zoom_tap_animation: ^1.1.0
  # flutter_slidable:
  # Test device package
  device_preview: ^1.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/locales/
