// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6qCy9IgV23l07r0sv_eh-oRsG4qJlxOI',
    appId: '1:502920115519:web:d74a884e3d778dfa624f8a',
    messagingSenderId: '502920115519',
    projectId: 'my-storage-ces',
    authDomain: 'my-storage-ces.firebaseapp.com',
    storageBucket: 'my-storage-ces.appspot.com',
    measurementId: 'G-FVNFRS9WHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEb_Z5PA6jLUIEOzcmQHeVXwq3eDKbAkE',
    appId: '1:502920115519:android:07af7d2e5ebf8e04624f8a',
    messagingSenderId: '502920115519',
    projectId: 'my-storage-ces',
    storageBucket: 'my-storage-ces.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5DoeCAisqqZSg0gXDo1MziMacLCn_Nxs',
    appId: '1:502920115519:ios:0e06e6292fe9481d624f8a',
    messagingSenderId: '502920115519',
    projectId: 'my-storage-ces',
    storageBucket: 'my-storage-ces.appspot.com',
    iosClientId:
        '502920115519-5r5ud7cqd4ufg3bsrai6756nbaj4o1e8.apps.googleusercontent.com',
    iosBundleId: 'com.example.cesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5DoeCAisqqZSg0gXDo1MziMacLCn_Nxs',
    appId: '1:502920115519:ios:75d5d12c96d53543624f8a',
    messagingSenderId: '502920115519',
    projectId: 'my-storage-ces',
    storageBucket: 'my-storage-ces.appspot.com',
    iosClientId:
        '502920115519-m3rlieei0hot4s3fsk9locqf7m6u297q.apps.googleusercontent.com',
    iosBundleId: 'com.example.cesApp.RunnerTests',
  );
}
